# Pull base image.
FROM ubuntu:14.04

# install Python 
RUN \
  apt-get update && \
  apt-get install -y software-properties-common python-software-properties && \
  apt-get -y install python3-dev python3-pip python-virtualenv && \ 
  rm -rf /var/lib/apt/lists/* 

# install Python libraries
RUN pip3 install numpy pandas nltk vaderSentiment textstat twython

# install MySQL and add configurations
RUN apt-get update && \
  echo "mysql-server-5.6 mysql-server/root_password password root" | sudo debconf-set-selections && \
  echo "mysql-server-5.6 mysql-server/root_password_again password root" | sudo debconf-set-selections && \
  apt-get -y install mysql-server-5.6 && \
  echo "secure-file-priv = \"\"" >> /etc/mysql/conf.d/my5.6.cnf
  
# install vader lexicon for sentiment analysis
RUN python3 -c 'import nltk;nltk.download("vader_lexicon")' && \
  python3 -c 'import nltk;nltk.download("punkt")'

# install r
# see https://www.digitalocean.com/community/tutorials/how-to-set-up-r-on-ubuntu-14-04
RUN \
  sh -c 'echo "deb http://cran.rstudio.com/bin/linux/ubuntu trusty/" >> /etc/apt/sources.list' && \
  gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-key E084DAB9 && \
  gpg -a --export E084DAB9 | apt-key add - && \
  apt-get update && \
  apt-get -y install r-base 

# install r packages, first later
RUN \
  R -e "install.packages(c('bindr', 'assertthat', 'bindrcpp', 'glue', 'magrittr', 'pkgconfig', 'rlang', 'R6', 'Rcpp', 'BH', 'plogr', 'getopt', 'digest', 'gtable', 'colorspace', 'lazyeval', 'plyr', 'stringi', 'RColorBrewer', 'dichromat', 'labeling', 'viridisLite'), repos = c('http://cran.rstudio.com/','http://cran.us.r-project.org'), dependencies = c('Depends'))" && \ 
  R -e "install.packages(c('fansi', 'utf8'), repos = c('http://cran.rstudio.com/','http://cran.us.r-project.org'), dependencies = c('Depends'))" && \ 
  R -e "install.packages(c('cli', 'crayon', 'pillar'), repos = c('http://cran.rstudio.com/','http://cran.us.r-project.org'), dependencies = c('Depends'))" && \ 
  R -e "install.packages('tibble', repos = c('http://cran.rstudio.com/','http://cran.us.r-project.org'), dependencies = c('Depends'))" && \ 
  R -e "install.packages(c('munsell'), repos = c('http://cran.rstudio.com/','http://cran.us.r-project.org'), dependencies = c('Depends'))" && \
  R -e "install.packages(c('reshape2', 'scales', 'stringr', 'withr'), repos = c('http://cran.rstudio.com/','http://cran.us.r-project.org'), dependencies = c('Depends'))" && \
  R -e "install.packages(c('ggplot2'), repos = c('http://cran.rstudio.com/','http://cran.us.r-project.org'), dependencies = c('Depends'))" && \
  R -e "install.packages('getopt', repos = c('http://cran.rstudio.com/','http://cran.us.r-project.org'), dependencies = c('Depends'))"

# install more r packages
RUN \
  R -e "install.packages('purrr', repos = c('http://cran.rstudio.com/','http://cran.us.r-project.org'), dependencies = c('Depends'))" && \
  R -e "install.packages(c( 'optparse', 'tidyselect'), repos = c('http://cran.rstudio.com/','http://cran.us.r-project.org'), dependencies = c('Depends'))" && \
  R -e "install.packages('dplyr', repos = c('http://cran.rstudio.com/','http://cran.us.r-project.org'), dependencies = c('Depends'))" 

# install even more r packages
RUN \
  R -e "install.packages(c('numDeriv', 'SQUAREM'), repos = c('http://cran.rstudio.com/','http://cran.us.r-project.org'), dependencies = c('Depends'))" && \
  R -e "install.packages(c('backports', 'lava'), repos = c('http://cran.rstudio.com/','http://cran.us.r-project.org'), dependencies = c('Depends'))" && \
  R -e "install.packages(c('DEoptimR', 'robustbase', 'tidyr', 'prodlim'), repos = c('http://cran.rstudio.com/','http://cran.us.r-project.org'), dependencies = c('Depends'))" && \
   R -e "install.packages(c('broom', 'tibble', 'ipred', 'dimRed', 'lubridate', 'timeDate', 'ddalpha', 'gower', 'RcppRoll', 'pls'), repos = c('http://cran.rstudio.com/','http://cran.us.r-project.org'), dependencies = c('Depends'))" && \
   R -e "install.packages(c('data.table', 'iterators'), repos = c('http://cran.rstudio.com/','http://cran.us.r-project.org'), dependencies = c('Depends'))" && \
  R -e "install.packages(c('foreach', 'ModelMetrics', 'reshape2', 'recipes'), repos = c('http://cran.rstudio.com/','http://cran.us.r-project.org'), dependencies = c('Depends'))" && \
  R -e "install.packages('caret', repos = c('http://cran.rstudio.com/','http://cran.us.r-project.org'), dependencies = c('Depends'))" && \
  R -e "install.packages('fastAdaboost', repos = c('http://cran.rstudio.com/','http://cran.us.r-project.org'), dependencies = c('Depends'))"
# even even more r packages
RUN \
  R -e "install.packages(c('forcats', 'hms', 'readr'), repos = c('http://cran.rstudio.com/','http://cran.us.r-project.org'), dependencies = c('Depends'))" && \
  R -e "install.packages('haven', repos = c('http://cran.rstudio.com/','http://cran.us.r-project.org'), dependencies = c('Depends'))" && \
  R -e "install.packages(c('httpuv', 'mime', 'jsonlite', 'xtable', 'sourcetools', 'later', 'promises'), repos = c('http://cran.rstudio.com/','http://cran.us.r-project.org'), dependencies = c('Depends'))" && \
  R -e "install.packages('e1071', repos = c('http://cran.rstudio.com/','http://cran.us.r-project.org'), dependencies = c('Depends'))" && \
  R -e "install.packages('htmltools', repos = c('http://cran.rstudio.com/','http://cran.us.r-project.org'), dependencies = c('Depends'))" && \
  R -e "install.packages('shiny', repos = c('http://cran.rstudio.com/','http://cran.us.r-project.org'), dependencies = c('Depends'))" && \
  R -e "install.packages(c('miniUI', 'rstudioapi', 'highr', 'classInt', 'labelled'), repos = c('http://cran.rstudio.com/','http://cran.us.r-project.org'), dependencies = c('Depends'))" && \  
  R -e "install.packages('questionr', repos = c('http://cran.rstudio.com/','http://cran.us.r-project.org'), dependencies = c('Depends'))" && \
  R -e "install.packages('combinat', repos = c('http://cran.rstudio.com/','http://cran.us.r-project.org'), dependencies = c('Depends'))" && \
  R -e "install.packages('klaR', repos = c('http://cran.rstudio.com/','http://cran.us.r-project.org'), dependencies = c('Depends'))"


# add scripts
ADD extraction extraction

ADD modeling modeling

ADD utils utils

ADD gardner.py /

# start mysql
RUN service mysql start

# define entrypoint
ENTRYPOINT ["python3", "gardner.py"]





